<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="log_request_error_messages" skipped="0" tests="1" time="58.53" timestamp="2022-05-23T16:44:41">
	<testcase classname="LogRequestVerifySearchTextError" name="log_request_error_messages">
		<failure message="BLOCKED: Exception: retry" type="BLOCKED"/>
		<system-out>16:43:42 INFO  ==============================================================
16:43:42 INFO  Id:    log_request_error_messages
16:43:42 INFO  Dir:   log_request_end_to_end/
16:43:42 INFO  Title: Validate end to end behaviour for the log request operation check for error messages
16:43:42 INFO  ==============================================================
16:43:44 INFO  EnvironmentC8y Setup
16:43:44 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
16:43:44 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 2 seconds
16:43:44 INFO  Delaying execution by 9 seconds
16:44:08 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
16:44:08 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
16:44:09 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
16:44:09 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
16:44:10 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
16:44:11 INFO  Executed sudo&lt;move_logs&gt;, exit status 0
16:44:11 INFO  log response None
16:44:11 WARN  retry, retrying in 1 seconds...
16:44:12 INFO  log response None
16:44:12 WARN  retry, retrying in 1 seconds...
16:44:14 INFO  log response None
16:44:14 WARN  retry, retrying in 1 seconds...
16:44:15 INFO  log response None
16:44:15 WARN  retry, retrying in 1 seconds...
16:44:16 INFO  log response None
16:44:16 WARN  retry, retrying in 1 seconds...
16:44:17 INFO  log response None
16:44:17 WARN  retry, retrying in 1 seconds...
16:44:18 INFO  log response None
16:44:18 WARN  retry, retrying in 1 seconds...
16:44:20 INFO  log response None
16:44:20 WARN  retry, retrying in 1 seconds...
16:44:21 INFO  log response None
16:44:21 WARN  retry, retrying in 1 seconds...
16:44:22 INFO  log response None
16:44:22 WARN  retry, retrying in 1 seconds...
16:44:23 INFO  log response None
16:44:23 WARN  retry, retrying in 1 seconds...
16:44:24 INFO  log response None
16:44:24 WARN  retry, retrying in 1 seconds...
16:44:26 INFO  log response None
16:44:26 WARN  retry, retrying in 1 seconds...
16:44:27 INFO  log response None
16:44:27 WARN  retry, retrying in 1 seconds...
16:44:28 INFO  log response None
16:44:28 WARN  retry, retrying in 1 seconds...
16:44:29 INFO  log response None
16:44:29 WARN  retry, retrying in 1 seconds...
16:44:31 INFO  log response None
16:44:31 WARN  retry, retrying in 1 seconds...
16:44:32 INFO  log response None
16:44:32 WARN  retry, retrying in 1 seconds...
16:44:33 INFO  log response None
16:44:33 WARN  retry, retrying in 1 seconds...
16:44:34 INFO  log response None
16:44:34 WARN  Exception occurred while running test - retry
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1296, in __call__
    self.testObj.validate()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/run.py&quot;, line 43, in validate
    self.assertThat(&quot;True == value&quot;, value=self.wait_until_logs_retrieved())
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py&quot;, line 232, in fun
    return caller(func, *(extras + args), **kw)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py&quot;, line 74, in retry_decorator
    logger)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py&quot;, line 33, in __retry_internal
    return f()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/run.py&quot;, line 52, in wait_until_logs_retrieved
    raise Exception(&quot;retry&quot;)
Exception: retry
16:44:35 WARN  Exception: retry ... blocked 
16:44:35 INFO  
16:44:35 INFO  cleanup:
16:44:35 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
16:44:36 INFO  Executed sudo&lt;rm_tmp_logs&gt;, exit status 0
16:44:36 INFO  Executed sudo&lt;send_failed&gt;, exit status 0
16:44:40 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
16:44:41 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
16:44:41 INFO  
16:44:41 INFO  Test duration: 58.53 secs
16:44:41 INFO  Test final outcome:  BLOCKED
16:44:41 INFO  Test outcome reason: Exception: retry
16:44:41 INFO  
</system-out>
	</testcase>
</testsuite>
