2022-06-20 17:49:06,983 INFO  ==============================================================
2022-06-20 17:49:06,984 INFO  Id:    SoftwareManagement.sm_apt_install_remove_multiple_mixed
2022-06-20 17:49:06,985 INFO  Dir:   software_management_end_to_end/
2022-06-20 17:49:06,986 INFO  Title: Validate end to end behaviour for the apt plugin for multiple packages with mixed versions
2022-06-20 17:49:06,987 INFO  ==============================================================
2022-06-20 17:49:07,032 INFO  Using sw id database: {'asciijump': '5475369', 'robotfindskitten': '5474869', 'squirrel3': '5475279', 'rolldice': '5152439', 'moon-buggy': '5439204', 'apple': '5495053', 'banana': '5494888', 'cherry': '5495382', 'watermelon': '5494510', 'registry': '8018911', 'hello-world': '8021526', 'docker/getting-started': '8021973', 'alpine': '7991792'}
2022-06-20 17:49:07,033 INFO  EnvironmentC8y Setup
2022-06-20 17:49:07,898 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-06-20 17:49:08,042 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
2022-06-20 17:49:08,044 INFO  Delaying execution by 6 seconds
2022-06-20 17:49:27,894 INFO  Executed sudo<tedge_connect_c8y>, exit status 0, duration 13 secs
2022-06-20 17:49:28,562 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-06-20 17:49:29,076 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-06-20 17:49:29,590 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-06-20 17:49:31,830 INFO  State of current operation: SUCCESSFUL
2022-06-20 17:49:32,063 INFO  Assert that (False == value) with value=False ... passed
2022-06-20 17:49:32,288 INFO  Assert that (False == value) with value=False ... passed
2022-06-20 17:49:32,529 INFO  Assert that (False == value) with value=False ... passed
2022-06-20 17:49:32,766 INFO  Assert that (False == value) with value=False ... passed
2022-06-20 17:49:33,001 INFO  Package moon-buggy is installed
2022-06-20 17:49:33,036 WARN  Assert that (False == value) with value=True ... failed 
2022-06-20 17:49:34,466 INFO  Response status: 201
2022-06-20 17:49:34,469 INFO  Response to action: {
    "creationTime": "2022-06-20T17:49:34.399Z",
    "deviceName": "m32sd10a",
    "deviceId": "20354757",
    "self": "https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/20362872",
    "id": "20362872",
    "status": "PENDING",
    "description": "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]",
    "c8y_SoftwareUpdate": [
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        },
        {
            "name": "robotfindskitten",
            "action": "install",
            "id": "5474869",
            "version": " ",
            "url": " "
        },
        {
            "name": "squirrel3",
            "action": "install",
            "id": "5475279",
            "version": "3.1-7::apt",
            "url": " "
        },
        {
            "name": "rolldice",
            "action": "install",
            "id": "5152439",
            "version": "1.16-1+b1",
            "url": " "
        },
        {
            "name": "moon-buggy",
            "action": "install",
            "id": "5439204",
            "version": "1:1.0.51-12",
            "url": " "
        },
        {
            "name": "asciijump",
            "action": "install",
            "id": "5475369",
            "version": "::apt",
            "url": " "
        }
    ]
}
2022-06-20 17:49:34,470 INFO  Started operation: {'creationTime': '2022-06-20T17:49:34.399Z', 'deviceName': 'm32sd10a', 'deviceId': '20354757', 'self': 'https://t493319102.eu-latest.cumulocity.com/devicecontrol/operations/20362872', 'id': '20362872', 'status': 'PENDING', 'description': "Apply software changes, triggered from PySys: [{'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}, {'action': 'install', 'id': '5474869', 'name': 'robotfindskitten', 'url': ' ', 'version': ' '}, {'action': 'install', 'id': '5475279', 'name': 'squirrel3', 'url': ' ', 'version': '3.1-7::apt'}, {'action': 'install', 'id': '5152439', 'name': 'rolldice', 'url': ' ', 'version': '1.16-1+b1'}, {'action': 'install', 'id': '5439204', 'name': 'moon-buggy', 'url': ' ', 'version': '1:1.0.51-12'}, {'action': 'install', 'id': '5475369', 'name': 'asciijump', 'url': ' ', 'version': '::apt'}]", 'c8y_SoftwareUpdate': [{'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}, {'name': 'robotfindskitten', 'action': 'install', 'id': '5474869', 'version': ' ', 'url': ' '}, {'name': 'squirrel3', 'action': 'install', 'id': '5475279', 'version': '3.1-7::apt', 'url': ' '}, {'name': 'rolldice', 'action': 'install', 'id': '5152439', 'version': '1.16-1+b1', 'url': ' '}, {'name': 'moon-buggy', 'action': 'install', 'id': '5439204', 'version': '1:1.0.51-12', 'url': ' '}, {'name': 'asciijump', 'action': 'install', 'id': '5475369', 'version': '::apt', 'url': ' '}]}
2022-06-20 17:49:36,685 INFO  State of operation 20362872 : PENDING
2022-06-20 17:49:38,910 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:41,124 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:43,346 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:45,560 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:47,784 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:50,568 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:53,279 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:55,678 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:49:58,207 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:00,427 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:02,645 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:04,878 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:07,093 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:09,340 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:11,680 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:14,060 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:16,412 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:19,168 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:21,423 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:23,653 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:25,876 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:28,588 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:30,808 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:33,059 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:35,353 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:37,561 INFO  State of operation 20362872 : EXECUTING
2022-06-20 17:50:40,447 WARN  ConnectionError occurred while running test - ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pi/env-pysys/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1294, in __call__
    self.testObj.execute()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_apt_install_remove_multiple_mixed/run.py", line 89, in execute
    self.wait_until_succcess()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 324, in wait_until_succcess
    self.wait_until_status("SUCCESSFUL")
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 354, in wait_until_status
    current_status = self.get_status_of_operation()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/environment_sm_management.py", line 300, in get_status_of_operation
    req = requests.get(url, headers=self.header, timeout=self.timeout_req)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-06-20 17:50:40,663 WARN  ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) ... blocked 
2022-06-20 17:50:40,664 INFO  
2022-06-20 17:50:40,665 INFO  cleanup:
2022-06-20 17:50:46,613 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-06-20 17:50:47,226 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-06-20 17:50:47,231 INFO  
2022-06-20 17:50:47,232 INFO  Test duration: 100.26 secs
2022-06-20 17:50:47,233 INFO  Test final outcome:  BLOCKED
2022-06-20 17:50:47,234 INFO  Test outcome reason: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) (+1 other failures)
2022-06-20 17:50:47,235 INFO  
